on:
  push:
    tags: 
    - '*'

jobs:
  generate-release:
    runs-on: ubuntu-latest
    name: Create release from a given tag
    container:
      image: docker://vrjuliao/changelog-autogen:0.1
    
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global url.git@github.com:.insteadOf https://github.com/

      - name: Create tag
        id: create_tag
        run: |
          if [[ "${{ github.event_name }}" == "schedule" ]]; then
            tag=v$(date +%Y%m%d.%H%M%S)
          else
            tag=$(basename "${{ github.ref }}")
          fi
          echo "::set-output name=tag::$tag"

      - name: Show tag
        id: show_tag
        run: |
             echo $tag_name
        env:
          tag_name: ${{ steps.create_tag.outputs.tag }}

      - name: Add SSH key
        env:
          cred: ${{ secrets.SSH_KEY }}
        run: |
              mkdir -p /root/.ssh
              echo -e $cred > /root/.ssh/id_ed25519
              ssh-keyscan -t ed25519 -H github.com >> /root/.ssh/known_hosts
              chmod 600 /root/.ssh/id_ed25519
              cat <<EOF >/root/.ssh/config
              Hostname github.com
              IdentityFile /root/.ssh/id_ed25519
              StrictHostKeyChecking no
              EOF
      
      - name: cloning private-repo
        run: git clone git@github.com:cyralinc/devops.git /tmp/devops

      - name: listing
        id: list
        run: ls /tmp/devops