on:
  push:
    tags: 
    - '*'

jobs:
  generate-release:
    runs-on: ubuntu-latest
    name: Create release from a given tag
    container:
      image: docker://vrjuliao/changelog-autogen:0.1
    
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set git user
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global url.git@github.com:.insteadOf https://github.com/

      - name: Add SSH key
        env:
          cred: ${{ secrets.SSH_KEY }}
        run: |
              mkdir -p /root/.ssh
              echo -e $cred > /root/.ssh/id_ed25519
              ssh-keyscan -t ed25519 -H github.com >> /root/.ssh/known_hosts
              chmod 600 /root/.ssh/id_ed25519
              cat <<EOF >/root/.ssh/config
              Hostname github.com
              IdentityFile /root/.ssh/id_ed25519
              StrictHostKeyChecking no
              EOF

      - name: Create tag
        id: create_tag
        run: |
          tag=$(basename "${{ github.ref }}")
          echo "::set-output name=tag::$tag"

      - name: Show tag
        id: show_tag
        run: |
            echo $tag_name
        env:
          tag_name: ${{ steps.create_tag.outputs.tag }}

      - name: Generate changelog
        id: changelog_generation
        run: /changelog-autogen/generator -tag=$tag_name `pwd`
        env:
          tag_name: ${{ steps.create_tag.outputs.tag }}

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ steps.create_tag.outputs.tag }}
          release_name: Release ${{ steps.create_tag.outputs.tag }}
          body_path: ./CHANGELOG.md
          draft: true
          prerelease: false

      - name: Publish release
        uses: StuYarrow/publish-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          id: ${{ steps.create_release.outputs.id }}
