on: [push]

jobs:
  generate-release:
    runs-on: ubuntu-latest
    name: Create release from a given tag
    container:
      image: docker://vrjuliao/changelog-autogen:0.1
    
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - uses: actions/checkout@v2
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global url.git@github.com:.insteadOf https://github.com/

      - name: Add SSH key
        env:
          cred: ${{ secrets.SSH_KEY }}
        run: |
            mkdir -p /root/.ssh
            cat <<EOF >/root/.ssh/config
            # Replace example.com with the hostname of the machine
            # you're SSH-ing into
            ssh-keyscan github.com >> /home/runner/.ssh/known_hosts
            # DOKKU_SSH_KEY is the name of the repository secret
            echo $cred
            echo $cred > /home/runner/.ssh/id_rsa
            chmod 600 /home/runner/.ssh/id_rsa
      
      - name: listing
        id: list
        run: ls /changelog-autogen

      - name: cloning private-repo
        run: git clone git@github.com:cyralinc/devops.git